[features]
seeds = false
skip-lint = false

[programs.localnet]
savact_payment = "NEku86HDWM6YZoHZG2oBX7rei5LX8Kbq8b4bJXUW4Zm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
client = "yarn run ts-node client/*.ts"
